# Generated by Django 3.1.7 on 2021-03-24 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("funds_service", "0001_initial"),
        ("applications_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="fund",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="funds_service.fund",
            ),
            preserve_default=False,
        ),
    ]
