# Generated by Django 3.1.7 on 2021-03-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications_service", "0002_application_fund"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="title",
            field=models.CharField(default="old application", max_length=255),
            preserve_default=False,
        ),
    ]
