# Generated by Django 3.1.7 on 2021-03-30 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("funds_service", "0006_auto_20210330_0655"),
        ("applications_service", "0005_summablecommitment"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountableOutput",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("committed_quantity", models.FloatField()),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="countable_outputs",
                        to="applications_service.application",
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_outputs",
                        to="funds_service.countablecriterion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SummableOutput",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("committed_quantity", models.FloatField()),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summable_outputs",
                        to="applications_service.application",
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_outputs",
                        to="funds_service.summablecriterion",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="summablecommitment",
            name="application",
        ),
        migrations.RemoveField(
            model_name="summablecommitment",
            name="criterion",
        ),
        migrations.DeleteModel(
            name="CountableCommitment",
        ),
        migrations.DeleteModel(
            name="SummableCommitment",
        ),
    ]
