version: "3.9"
services:
  applicationui:
    build: application-ui
    command: npm run start:dev
    environment:
      # Environment vars are employed at BUILD TIME by WEBPACK. They are not
      # exposed "into" the JS / React app.
      API_HOST: http://localhost:8000
    ports:
      - "8080:8080"
    volumes:
      - ./application-ui:/usr/src/app
    depends_on:
      - webservices

  webservices:
    build: web-services
    environment:
      DJANGO_SECRET_KEY: NotASecret
      PYTHONUNBUFFERED: 1
    ports:
      - "8000:8000"
    volumes:
      - ./web-services:/usr/src/app
