# Generated by Django 3.1.7 on 2021-03-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fund",
            name="short_description",
            field=models.CharField(
                default="old fund",
                help_text="Give a short description, shown to the Applicant in the choice list",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fund",
            name="name",
            field=models.CharField(
                help_text="Give a short name to this Fund", max_length=255
            ),
        ),
    ]
