# Generated by Django 3.1.7 on 2021-03-25 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("funds_service", "0002_auto_20210325_0923"),
    ]

    operations = [
        migrations.CreateModel(
            name="SummableCriterion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='Singular name of the criterion (e.g. "Floorspace")',
                        max_length=255,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text='The unit of measurement (e.g. "m2")', max_length=255
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summable_criteria",
                        to="funds_service.fund",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Summable criteria",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="CountableCriterion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='Plural name of the criterion (e.g. "Rail routes")',
                        max_length=255,
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="countable_criteria",
                        to="funds_service.fund",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Countable criteria",
                "ordering": ["label"],
            },
        ),
    ]
