# Generated by Django 3.1.7 on 2021-03-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds_service", "0003_countablecriterion_summablecriterion"),
    ]

    operations = [
        migrations.AddField(
            model_name="countablecriterion",
            name="guidance_notes",
            field=models.TextField(
                default="some guidance notes",
                help_text="Provide information to assist the applicant in understanding the correct interpretation of this commitment",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="summablecriterion",
            name="guidance_notes",
            field=models.TextField(
                default="some guidance notes",
                help_text="Provide information to assist the applicant in understanding the correct interpretation of this commitment",
            ),
            preserve_default=False,
        ),
    ]
