# Generated by Django 3.1.7 on 2021-03-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds_service", "0004_auto_20210325_1450"),
    ]

    operations = [
        migrations.AddField(
            model_name="fund",
            name="long_description",
            field=models.TextField(
                default="long description",
                help_text="Provide a more detailed explanation of this Fund and its purpose, some details of its commitment criteria, etc. Bear in mind the potential Applicant will be searching against this content so be sure to include helpful keywords.",
            ),
            preserve_default=False,
        ),
    ]
