# Generated by Django 3.1.7 on 2021-03-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds_service", "0005_fund_long_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countablecriterion",
            name="guidance_notes",
            field=models.TextField(
                help_text="Provide information to assist the applicant in understanding the correct interpretation of this output"
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="long_description",
            field=models.TextField(
                help_text="Provide a more detailed explanation of this Fund and its purpose, some details of its output criteria, etc. Bear in mind the potential Applicant will be searching against this content so be sure to include helpful keywords."
            ),
        ),
        migrations.AlterField(
            model_name="summablecriterion",
            name="guidance_notes",
            field=models.TextField(
                help_text="Provide information to assist the applicant in understanding the correct interpretation of this output"
            ),
        ),
    ]
