# Generated by Django 3.1.7 on 2021-03-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds_service", "0007_auto_20210330_0934"),
    ]

    operations = [
        migrations.AddField(
            model_name="countablecriterion",
            name="output_category",
            field=models.TextField(
                choices=[
                    ("Transport - Rail", "Transport - Rail"),
                    ("Transport - Road", "Transport - Road"),
                    ("Transport - Cycleways", "Transport - Cycleways"),
                    ("Transport - Pedestrian path", "Transport - Pedestrian path"),
                    (
                        "Skills & Education - Floorspace",
                        "Skills & Education - Floorspace",
                    ),
                    (
                        "Skills & Education - Students & learners",
                        "Skills & Education - Students & learners",
                    ),
                    ("Connectivity - Public spaces", "Connectivity - Public spaces"),
                    ("Connectivity - Homes", "Connectivity - Homes"),
                ],
                default="Transport - Rail",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="summablecriterion",
            name="output_category",
            field=models.TextField(
                choices=[
                    ("Transport - Rail", "Transport - Rail"),
                    ("Transport - Road", "Transport - Road"),
                    ("Transport - Cycleways", "Transport - Cycleways"),
                    ("Transport - Pedestrian path", "Transport - Pedestrian path"),
                    (
                        "Skills & Education - Floorspace",
                        "Skills & Education - Floorspace",
                    ),
                    (
                        "Skills & Education - Students & learners",
                        "Skills & Education - Students & learners",
                    ),
                    ("Connectivity - Public spaces", "Connectivity - Public spaces"),
                    ("Connectivity - Homes", "Connectivity - Homes"),
                ],
                default="Transport - Rail",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
