# Generated by Django 3.1.7 on 2021-03-30 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("funds_service", "0008_auto_20210330_1004"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="countablecriterion",
            options={
                "ordering": ["output_category", "label"],
                "verbose_name_plural": "Countable criteria",
            },
        ),
        migrations.AlterModelOptions(
            name="summablecriterion",
            options={
                "ordering": ["output_category", "label"],
                "verbose_name_plural": "Summable criteria",
            },
        ),
    ]
